// <auto-generated />
using System;
using HelpDesk.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HelpDesk.Api.Migrations
{
    [DbContext(typeof(HelpDeskDbContext))]
    partial class HelpDeskDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HelpDesk.Api.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RaisedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 8, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Getting error 503 when logging into Outlook on web.",
                            Priority = "High",
                            RaisedBy = "John Doe",
                            Status = "Open",
                            Title = "Cannot access corporate email"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 8, 2, 11, 30, 0, 0, DateTimeKind.Utc),
                            Description = "The VPN connection drops every 15 minutes on Windows 11.",
                            Priority = "Medium",
                            RaisedBy = "Jane Smith",
                            Status = "In Progress",
                            Title = "VPN connection drops"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 8, 3, 14, 15, 0, 0, DateTimeKind.Utc),
                            Description = "Requesting a secondary 27-inch monitor for development workspace.",
                            Priority = "Low",
                            RaisedBy = "Alice Johnson",
                            Status = "Closed",
                            Title = "New monitor request"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
